### ISSUE TITLE
DB 설정 파일이 없으면 알아서 생성해야 되는데 에러가 남

### ISSUE THREAD

**Issue by byung-u** [byung-u/FindTheTreasure#2]
Traceback (most recent call last):
  File "/usr/local/bin/find_the_treasure", line 4, in <module>
    __import__('pkg_resources').run_script('find-the-treasure==0.5.0', 'find_the_treasure')
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1501, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.6/site-packages/find_the_treasure-0.5.0-py3.6.egg/EGG-INFO/scripts/find_the_treasure", line 6, in <module>
  File "/usr/local/lib/python3.6/site-packages/find_the_treasure-0.5.0-py3.6.egg/find_the_treasure/main.py", line 270, in main
    sqlite3 = UseSqlite3()
  File "/usr/local/lib/python3.6/site-packages/find_the_treasure-0.5.0-py3.6.egg/find_the_treasure/ft_sqlite3.py", line 10, in __init__
    self.conn = sqlite3.connect(defaults.DB_FILE_PATH)
sqlite3.OperationalError: unable to open database file

**Comment by byung-u** [comment]
sqlite3 = UseSqlite3()   

만들었던 클래스 객체 받아오는 로직의 
위치가 잘 못되서 에러가 발생
